#!/bin/sh

JTG_CLASSPATH="`dirname $0`/hadoop-cacti-jtg.jar"
JTG_CLASSNAME="com.jointhegrid.hadoopjmx.hadoop_0_20.alerting.FSNamesystemStatusFilesTotalCheck"

jmxURL=$1
user=$2
pass=$3
object=$4
warn=$5
crit=$6
java -cp ${JTG_CLASSPATH} ${JTG_CLASSNAME} $jmxURL $user $pass $object $warn $crit